"use client";
import { useState } from "react";
import { Bot, CheckCircle2, Send, Sparkles, Wand2, Workflow } from "lucide-react";
import AppShell from "@/components/AppShell";

type Message={role:"user"|"assistant";text:string};
type CreatedWorkflow={id:string;name:string;trigger:string};

export default function AIAssistant(){
 const [message,setMessage]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [created,setCreated]=useState<CreatedWorkflow|null>(null);
 async function ask(prompt?:string, shouldCreate=false){const text=(prompt??message).trim();if(!text||loading)return;setMessages(m=>[...m,{role:"user",text}]);setMessage("");setLoading(true);setError("");setCreated(null);try{const res=await fetch("/api/ai/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,createWorkflow:shouldCreate})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Unable to reach AI");setMessages(m=>[...m,{role:"assistant",text:body.text}]);if(body.workflow)setCreated(body.workflow)}catch(e){setError(e instanceof Error?e.message:"AI request failed")}finally{setLoading(false)}}
 return <AppShell><main className="min-h-screen px-6 py-8 lg:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-start justify-between gap-6"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-violet-300"><Sparkles size={14}/>FlowPilot AI</div><h1 className="mt-3 text-3xl font-semibold tracking-tight">Your operations copilot.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Describe a process, ask a question, or tell me what you want to automate.</p></div><div className="rounded-2xl border border-violet-400/20 bg-gradient-to-br from-violet-500/15 to-fuchsia-500/10 p-4"><Bot className="text-violet-300"/></div></div>
 <section className="mt-8 overflow-hidden rounded-[2rem] border border-white/[.08] bg-gradient-to-br from-white/[.045] via-violet-500/[.025] to-fuchsia-500/[.04] shadow-2xl shadow-violet-950/10"><div className="min-h-[430px] space-y-5 p-6 sm:p-8">{messages.length===0?<div className="flex min-h-[360px] flex-col items-center justify-center text-center"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-gradient-to-br from-violet-500/20 to-fuchsia-500/20 text-violet-300"><Bot size={28}/></div><h2 className="mt-5 text-xl font-semibold">What can I help you automate?</h2><p className="mt-2 max-w-md text-sm leading-6 text-zinc-600">Try asking me to create a workflow. Your conversation will stay visible while you work.</p></div>:messages.map((m,i)=><div key={i} className={`flex gap-3 ${m.role==="user"?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.role==="user"?"bg-violet-500 text-white":"border border-white/[.07] bg-white/[.035] text-zinc-300"}`}>{m.text}</div></div>)}{loading&&<div className="flex items-center gap-3 text-sm text-zinc-500"><div className="grid h-8 w-8 place-items-center rounded-xl bg-violet-500/10"><Bot size={15} className="text-violet-300"/></div>FlowPilot is thinking...</div>}{created&&<div className="flex items-center gap-3 rounded-2xl border border-emerald-400/15 bg-emerald-400/[.06] p-4"><CheckCircle2 className="text-emerald-300" size={19}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-emerald-200">Workflow created</p><p className="mt-1 truncate text-xs text-zinc-500">{created.name} · {created.trigger}</p></div><a href="/workflows" className="text-xs font-semibold text-emerald-200 hover:text-white">Open →</a></div>}{error&&<div className="rounded-xl border border-red-400/15 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}</div>
 <form onSubmit={e=>{e.preventDefault();ask()}} className="m-5 flex gap-2 rounded-2xl border border-white/[.08] bg-[#0b0d13] p-2 shadow-inner sm:m-6"><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Tell FlowPilot what you want to automate..." className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none placeholder:text-zinc-700"/><button disabled={!message.trim()||loading} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-gradient-to-r from-violet-500 to-fuchsia-500 text-white disabled:opacity-40"><Send size={17}/></button></form></section>
 <div className="mt-5 grid gap-3 md:grid-cols-3">{[["Create support triage","Create a workflow that summarizes support tickets and routes urgent issues."],["Automate reports","Create a workflow that prepares a weekly operations report."],["Invoice approvals","Create a workflow for invoice review and approval."]].map(([title,prompt])=><button key={title} onClick={()=>ask(prompt,true)} className="group flex items-start gap-3 rounded-2xl border border-white/[.07] bg-white/[.025] p-4 text-left transition hover:-translate-y-0.5 hover:border-violet-400/25 hover:bg-violet-500/[.05]"><span className="rounded-xl bg-violet-500/10 p-2 text-violet-300"><Wand2 size={16}/></span><span><span className="block text-sm font-semibold text-zinc-200">{title}</span><span className="mt-1 block text-xs leading-5 text-zinc-600">{prompt}</span></span></button>)}</div></div></main></AppShell>;
}